#include "keymap.h" 

const uint8_t adc_key_code[KEY_ADC_KEY_NUM] = {
  [_KEY_A_]             = HID_KEY_A,
  [_KEY_B_]             = HID_KEY_B,
  [_KEY_C_]             = HID_KEY_C,
  [_KEY_D_]             = HID_KEY_D,
  [_KEY_E_]             = HID_KEY_E,
  [_KEY_F_]             = HID_KEY_F,
  [_KEY_G_]             = HID_KEY_G,
  [_KEY_H_]             = HID_KEY_H,
  [_KEY_I_]             = HID_KEY_I,
  [_KEY_J_]             = HID_KEY_J,
  [_KEY_K_]             = HID_KEY_K,
  [_KEY_L_]             = HID_KEY_L,
  [_KEY_M_]             = HID_KEY_M,
  [_KEY_N_]             = HID_KEY_N,
  [_KEY_O_]             = HID_KEY_O,
  [_KEY_P_]             = HID_KEY_P,
  [_KEY_Q_]             = HID_KEY_Q,
  [_KEY_R_]             = HID_KEY_R,
  [_KEY_S_]             = HID_KEY_S,
  [_KEY_T_]             = HID_KEY_T,
  [_KEY_U_]             = HID_KEY_U,
  [_KEY_V_]             = HID_KEY_V,
  [_KEY_W_]             = HID_KEY_W,
  [_KEY_X_]             = HID_KEY_X,
  [_KEY_Y_]             = HID_KEY_Y,
  [_KEY_Z_]             = HID_KEY_Z,
  [_KEY_1_]             = HID_KEY_1,
  [_KEY_2_]             = HID_KEY_2,
  [_KEY_3_]             = HID_KEY_3,
  [_KEY_4_]             = HID_KEY_4,
  [_KEY_5_]             = HID_KEY_5,
  [_KEY_6_]             = HID_KEY_6,
  [_KEY_7_]             = HID_KEY_7,
  [_KEY_8_]             = HID_KEY_8,
  [_KEY_9_]             = HID_KEY_9,
  [_KEY_0_]             = HID_KEY_0,
  [_KEY_ENTER_]         = HID_KEY_ENTER,
  [_KEY_ESCAPE_]        = HID_KEY_ESCAPE,
  [_KEY_BACKSPACE_]     = HID_KEY_BACKSPACE,
  [_KEY_TAB_]           = HID_KEY_TAB,
  [_KEY_SPACE_]         = HID_KEY_SPACE,
  [_KEY_MINUS_]         = HID_KEY_MINUS,
  [_KEY_EQUAL_]         = HID_KEY_EQUAL,
  [_KEY_BRACKET_LEFT_]  = HID_KEY_BRACKET_LEFT,
  [_KEY_BRACKET_RIGHT_] = HID_KEY_BRACKET_RIGHT,
  [_KEY_BACKSLASH_]     = HID_KEY_BACKSLASH,
  [_KEY_SEMICOLOW_]     = HID_KEY_SEMICOLOW,
  [_KEY_APOSTROPHE_]    = HID_KEY_APOSTROPHE,
  [_KEY_COMMA_]         = HID_KEY_COMMA,
  [_KEY_DOT_]           = HID_KEY_DOT,
  [_KEY_SLASH_]         = HID_KEY_SLASH,
  [_KEY_CAPSLOCK_]      = HID_KEY_CAPSLOCK,
  [_KEY_INSERT_]        = HID_KEY_INSERT,
  [_KEY_PAGEUP_]        = HID_KEY_PAGEUP,
  [_KEY_DELETE_]        = HID_KEY_DELETE,
  [_KEY_PAGEDOWN_]      = HID_KEY_PAGEDOWN,
  [_KEY_RIGHT_]         = HID_KEY_RIGHT,
  [_KEY_LEFT_]          = HID_KEY_LEFT,
  [_KEY_DOWN_]          = HID_KEY_DOWN,
  [_KEY_UP_]            = HID_KEY_UP,
  [_LEFT_CTRL_]         = KEY_LEFT_CTRL,
  [_LEFT_SHIFT_]        = KEY_LEFT_SHIFT,
  [_LEFT_ALT_]          = KEY_LEFT_ALT,
  [_LEFT_META_]         = KEY_LEFT_META,
  [_RIGHT_CTRL_]        = KEY_RIGHT_CTRL,
  [_RIGHT_SHIFT_]       = KEY_RIGHT_SHIFT,
  [_RIGHT_ALT_]         = KEY_RIGHT_ALT,
  [_RIGHT_META_]        = KEY_RIGHT_META
};





